# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: score.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'score.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bscore.proto\x12\x05score\"\x1a\n\x0bPaperBundle\x12\x0b\n\x03ids\x18\x01 \x03(\x0c\"\x07\n\x05\x45mpty\"=\n\x0fPopulateRequest\x12*\n\rpopulate_type\x18\x01 \x01(\x0e\x32\x13.score.PopulateType\"U\n\x16RedisPaperScoreRequest\x12\x11\n\tembedding\x18\x01 \x03(\x02\x12\x13\n\x0bnum_results\x18\x02 \x01(\r\x12\x13\n\x0b\x64\x61taset_ids\x18\x03 \x03(\x05\"O\n\x18RedisDatasetScoreRequest\x12\x11\n\tembedding\x18\x01 \x03(\x02\x12\x13\n\x0bnum_results\x18\x02 \x01(\r\x12\x0b\n\x03ids\x18\x03 \x03(\x05\"2\n\rScoreResponse\x12\x12\n\ndataset_id\x18\x01 \x01(\x05\x12\r\n\x05score\x18\x02 \x01(\x02*&\n\x0cPopulateType\x12\x0b\n\x07\x44\x61taset\x10\x00\x12\t\n\x05Paper\x10\x01\x32\xd8\x01\n\x0bScoreGetter\x12I\n\x0c\x44\x61tasetScore\x12\x1f.score.RedisDatasetScoreRequest\x1a\x14.score.ScoreResponse\"\x00\x30\x01\x12J\n\x0fRedisPaperScore\x12\x1d.score.RedisPaperScoreRequest\x1a\x14.score.ScoreResponse\"\x00\x30\x01\x12\x32\n\x08Populate\x12\x16.score.PopulateRequest\x1a\x0c.score.Empty\"\x00\x42\x36\n\x1bio.grpc.examples.routeguideB\x0fRouteGuideProtoP\x01\xa2\x02\x03RTGb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'score_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033io.grpc.examples.routeguideB\017RouteGuideProtoP\001\242\002\003RTG'
  _globals['_POPULATETYPE']._serialized_start=342
  _globals['_POPULATETYPE']._serialized_end=380
  _globals['_PAPERBUNDLE']._serialized_start=22
  _globals['_PAPERBUNDLE']._serialized_end=48
  _globals['_EMPTY']._serialized_start=50
  _globals['_EMPTY']._serialized_end=57
  _globals['_POPULATEREQUEST']._serialized_start=59
  _globals['_POPULATEREQUEST']._serialized_end=120
  _globals['_REDISPAPERSCOREREQUEST']._serialized_start=122
  _globals['_REDISPAPERSCOREREQUEST']._serialized_end=207
  _globals['_REDISDATASETSCOREREQUEST']._serialized_start=209
  _globals['_REDISDATASETSCOREREQUEST']._serialized_end=288
  _globals['_SCORERESPONSE']._serialized_start=290
  _globals['_SCORERESPONSE']._serialized_end=340
  _globals['_SCOREGETTER']._serialized_start=383
  _globals['_SCOREGETTER']._serialized_end=599
# @@protoc_insertion_point(module_scope)
